### ISSUE TITLE
Blog does not exist

### ISSUE THREAD

**Issue by abelard-school-csc** [Abelard-School-Computer-Science-Club/Club-Homepage#7]
When you click on "Blog" in the navigation bar, it brings you to a 404 page. Fix this problem (probably something to do with Github and Jekyll integration since this problem is not reproduce able locally)

**Comment by AndrewAMur** [comment]
Fixed. Problem with was with the "permalink" parameter in _config.yml. The solution was to add the following line at the end of the file:
`permalink: pretty`
It works now.
